### PR TITLE
Advanced Collision, Class System fixes, Scan Max Distance and Arena Size Enforcement

### PR DESCRIPTION
**Pull request by mcstoer**
**Description**

Added advanced collisions that use bot speed and angle to calculate damage taken.
Fixed a major issue with the class system not properly accommodating for server arguments such as -botaccrate and other mobility related arguments.
Added a max and minimum arena size that is enforced through the argument system.
Added a scanmaxdistance argument that limits the max distance a robot scan see another robot from.
Changed the ipc for scanReply to handle the newer max arena sizes.
Fixed spelling, inconsistent argument case, formatting and wording of -hitdamage and -allowclasses arguments. 

**Motivation and Context**

Advanced collisions was needed to be added to create more logical interactions with the bot and the environment.
Changes to the class system were necessary to fix the bug that the class system had related to the server arguments.
Arena size enforcement and scan max distance were added to fix how bots interacted at larger and smaller arena sizes.
Smaller changes such as spelling, inconsistent argument case, formatting and wording of -hitdamage and -allowclasses arguments were all changed to improve the quality of the code.

**Related Issue(s)**

#10, #63, #22, #58 , #57.

**Completeness**

Fully adds advanced collisions, scan max distance limiting and arena size enforcement.
Fully fixes the class system and its error with other server arguments.
_Does not update any of the readme_

**Testing**

There is possibly a bug related to advanced collisions and turning while hitting a wall.  This can cause the robot to take little to no damage. 

Otherwise it has been somewhat tested with 1000 test games with robot's implementing the class, advanced collision and scan max distance systems.

### CODE REVIEW

**Comment by dbakewel** [comment]
Your changes to the class system are not correct and introduce some big bugs. I want the scan fix so I'll back out the class changes first. Please leave the class system alone until @lsh010815 and I are done with it.  If there are issues then please file bug reports.

**Comment by mcstoer** [comment]
@dbakewel what big bugs are these? I have double checked all the multiplier calculations and have tested each classes damage taken and mobility.

**Comment by dbakewel** [comment]
Merged scan fix on command line git since github could not resolve conflicts

**Comment by dbakewel** [comment]
I may have been wrong about the class multipliers introducing bugs. It's fairer to say that it was too much change at once for me to understand without some context. Regardless, it needed work to mesh well with other ideas I have for classes so it needed to come out for now. I'd like to talk about this with you, me and @lsh010815.

**Pull request closed without merging**
